services:
  react-frontend:
    image: nginx:alpine
    container_name: react-nginx
    ports:
      - "80:80"
    volumes:
      - ./web/dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - network
  api:
    image: php:8.2-fpm
    container_name: api
    volumes: 
      - ./api:/var/www/html:ro
    networks:
      - network
    command: 
      /bin/sh -c "
        apt-get update 
        && apt-get install -y --no-install-recommends libpq-dev 
        && docker-php-ext-install pdo pdo_pgsql 
        && rm -rf /var/lib/apt/lists/* 
        && php-fpm"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: mydb
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - network

networks:
  network:
    driver: bridge
